export enum TimeOffRequestStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  SYNCING = 'SYNCING',
  SYNCED = 'SYNCED',
  FAILED_SYNC = 'FAILED_SYNC',
  CANCELLED = 'CANCELLED',
}
